version: '2.0'
services:
  db:
    container_name: zabo_develop_db
    image: mariadb:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - /home/jara/docker/mariadb/data:/var/lib/mysql
      - /home/jara/docker/mariadb/conf.d:/etc/mysql/conf.d
    ports:
      - "3306:3306"

  web:
    container_name: zabo_develop_server_joyb
    image: vk8520/zabo-base:0.4
    restart: always
    volumes:
      - /home/jara/zabo/zbo_api/zabo_api:/home/zabo/zabo_api
    command: ./home/zabo/zabo_api/start_up.sh
    ports: 
      - "16135:8080"
    links:
      - db

