# Generated by Django 2.0.2 on 2018-07-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zabouser',
            name='nickName',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
