# Generated by Django 2.0.2 on 2018-07-04 08:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_zabouser_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='zabouser',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='_zabouser_following_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
