# Generated by Django 2.0.2 on 2018-07-04 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_zabouser_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zabouser',
            name='nickName',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
