# Generated by Django 2.0.2 on 2018-07-12 09:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180711_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='zabouser',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('E', 'Etc')], default='E', max_length=1),
        ),
        migrations.AlterField(
            model_name='zabouser',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='_zabouser_following_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
