# Generated by Django 2.0.2 on 2018-07-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180712_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zabouser',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('E', 'Etc'), ('B', 'Blind')], default='B', max_length=1),
        ),
    ]
