# Generated by Django 2.0.2 on 2018-07-14 08:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20180712_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zabouser',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='follower', to=settings.AUTH_USER_MODEL),
        ),
    ]
