# Generated by Django 2.0.2 on 2018-07-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20180714_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='zabouser',
            name='sid',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
