# Generated by Django 2.0.2 on 2018-08-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20180714_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zabouser',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to='users/profile/'),
        ),
    ]
