# Generated by Django 2.0.2 on 2018-08-15 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20180806_2023'),
        ('users', '0011_auto_20180729_0813'),
    ]

    operations = [
    ]
