# Generated by Django 2.0.2 on 2018-08-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_merge_20180815_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='zabouser',
            name='is_sso',
            field=models.BooleanField(default=False),
        ),
    ]
