# Generated by Django 2.0.2 on 2018-05-02 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaboes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='zabo',
            name='posters_num',
            field=models.IntegerField(default=0),
        ),
    ]
