# Generated by Django 2.0.2 on 2018-07-11 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaboes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zabo',
            name='deadline',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
