# Generated by Django 2.0.2 on 2018-07-11 07:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaboes', '0002_zabo_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zabo',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 11, 7, 21, 48, 647997)),
        ),
    ]
