# Generated by Django 2.0.2 on 2018-07-02 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zaboes', '0004_auto_20180702_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zabo',
            name='title',
        ),
    ]
