# Generated by Django 2.0.2 on 2018-06-28 09:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zaboes', '0004_auto_20180628_0859'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('zabo', 'user')},
        ),
    ]
