# Generated by Django 2.0.2 on 2018-07-11 08:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('zaboes', '0004_auto_20180711_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zabo',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 11, 8, 1, 31, 686705, tzinfo=utc)),
        ),
    ]
