# Generated by Django 2.0.2 on 2018-07-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaboes', '0005_remove_zabo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='zabo',
            name='title',
            field=models.CharField(default='Title', max_length=50),
        ),
    ]
