# Generated by Django 2.0.2 on 2018-07-12 09:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('zaboes', '0005_auto_20180711_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zabo',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 12, 9, 21, 14, 224774, tzinfo=utc)),
        ),
    ]
