# Generated by Django 2.0.2 on 2018-06-29 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaboes', '0005_auto_20180628_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='zabo',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
