# Generated by Django 2.0.2 on 2018-06-29 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zaboes', '0006_zabo_like_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zabo',
            name='like_count',
        ),
    ]
