# Generated by Django 2.0.2 on 2018-07-02 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zaboes', '0006_zabo_title'),
        ('zaboes', '0004_auto_20180523_0828'),
    ]

    operations = [
    ]
