# Generated by Django 2.0.2 on 2018-07-14 08:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('zaboes', '0007_auto_20180714_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zabo',
            old_name='url',
            new_name='link_url',
        ),
        migrations.AlterField(
            model_name='zabo',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 14, 8, 55, 27, 636725, tzinfo=utc)),
        ),
    ]
