# Generated by Django 2.0.2 on 2018-07-02 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zaboes', '0008_auto_20180702_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='zaboUser',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
