# Generated by Django 2.0.2 on 2018-07-02 16:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zaboes', '0009_auto_20180702_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='zaboUser',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('zabo', 'user')},
        ),
    ]
