# Generated by Django 2.0.2 on 2018-07-15 06:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('zaboes', '0009_auto_20180715_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zabo',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 15, 6, 40, 39, 148281, tzinfo=utc)),
        ),
    ]
