# Generated by Django 2.0.2 on 2018-07-15 07:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('zaboes', '0010_auto_20180715_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zabo',
            old_name='founder',
            new_name='author',
        ),

    ]
