# Generated by Django 2.0.2 on 2018-07-29 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zaboes', '0012_auto_20180718_1137'),
        ('zaboes', '0012_auto_20180718_1156'),
    ]

    operations = [
    ]
