# Generated by Django 2.0.2 on 2018-08-30 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zaboes', '0013_merge_20180729_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZaboHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('zabo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='zaboes.Zabo')),
            ],
        ),
    ]
