# Generated by Django 2.0.2 on 2018-07-10 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zaboes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(blank=True, max_length=30)),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_adminnotification_related', related_query_name='notifications_adminnotifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommentReactionNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(blank=True, max_length=30)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_reaction', to='zaboes.Comment')),
                ('reactors', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_commentreactionnotification_related', related_query_name='notifications_commentreactionnotifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ZaboReactionNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(blank=True, max_length=30)),
                ('reactors', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_zaboreactionnotification_related', related_query_name='notifications_zaboreactionnotifications', to=settings.AUTH_USER_MODEL)),
                ('zabo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zabo_reaction', to='zaboes.Zabo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ZabpFollowingNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(blank=True, max_length=30)),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_zabpfollowingnotification_related', related_query_name='notifications_zabpfollowingnotifications', to=settings.AUTH_USER_MODEL)),
                ('zabo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zabo_following', to='zaboes.Zabo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
