# Generated by Django 2.0.2 on 2018-07-10 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zaboes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZaboFollowingNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(blank=True, max_length=30)),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_zabofollowingnotification_related', related_query_name='notifications_zabofollowingnotifications', to=settings.AUTH_USER_MODEL)),
                ('zabo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zabo_following', to='zaboes.Zabo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='zabpfollowingnotification',
            name='to',
        ),
        migrations.RemoveField(
            model_name='zabpfollowingnotification',
            name='zabo',
        ),
        migrations.DeleteModel(
            name='ZabpFollowingNotification',
        ),
    ]
