# Generated by Django 2.0.2 on 2018-07-10 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_zabofollowingnotification_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zabofollowingnotification',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_zabofollowingnotification_related_following', related_query_name='notifications_zabofollowingnotifications_following', to=settings.AUTH_USER_MODEL),
        ),
    ]
