# Generated by Django 2.0.2 on 2018-07-14 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_someonefollowingnotification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminnotification',
            options={'ordering': ['updated_time']},
        ),
        migrations.AlterModelOptions(
            name='someonefollowingnotification',
            options={'ordering': ['updated_time']},
        ),
    ]
